services:
  ts-beszel-hub:
    image: tailscale/tailscale:latest
    container_name: ts-beszel-hub
    hostname: beszel
    environment:
      - TS_AUTHKEY=tskey-client-k6dzsieVZ321CNTRL-77gE7hDNeEUHXJakDhrcEU1B6vAb2sYVR
      - TS_EXTRA_ARGS=--advertise-tags=tag:beszel
      - TS_SERVE_CONFIG=/config/beszel-hub.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - /volume1/docker/beszel-hub/tailscale/state:/var/lib/tailscale
      - /volume1/docker/beszel-hub/tailscale/config:/config
    restart: unless-stopped
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel-hub
    network_mode: service:ts-beszel-hub
    depends_on:
      - ts-beszel-hub
    volumes:
      - /volume1/docker/beszel-hub/beszel_data:/beszel_data
    ports:
      - '8090:8090'
    restart: unless-stopped